### ISSUE TITLE
Release the MVP version

### ISSUE THREAD

**Issue by ben-ryder** [Ben-Ryder/rcl#1]
**Describe your feature**
Release the MVP version

**Is your suggestion related to any problems?**
n/a

**Additional context**
n/a

**Comment by Ben-Ryder** [comment]
Although the MVP project has been release on pip, it is not yet in a stable state. (See issue #2). I will keep this issue open until the "Stable MVP Release" milestone is hit.

**Comment by ben-ryder** [comment]
Closed, #2 has been solved with PR #6 and release [v0.1.2](https://github.com/Ben-Ryder/rcl/releases/tag/v0.1.2).
